### ISSUE TITLE
can not add ofxKinectForWindows2.props

### ISSUE THREAD

**Issue by fdiba** [elliotwoods/ofxKinectForWindows2#54]
Hello,

I get few compile errors while trying to make work the first example. I think it is because I didn't add the "ofxKinectForWindows2.props" file to my project but I don't know how to do it.

Can you help me ?

I can't find the label "Add Existing Property Sheet..." in the "Property Manager" as explained in the readme file.

![capture](https://cloud.githubusercontent.com/assets/5859041/14763365/f5257b08-0993-11e6-8110-8d3ac4083274.PNG)

**Comment by elliotwoods** [comment]
It seems to be an openFrameworks version mismatch
I think I'm using a function there which isn't in 0.9.0
It's not harmful to remove that part. Just search for where the error is
coming up and remove the offending lines
They'll be related to an if statement
Just make it true instead of checking this missing function

**Comment by fdiba** [comment]
Thank you, it works!

This is the line that causes the problem in Device.cpp:

`auto mainWindow = std::static_pointer_cast<ofAppGLFWWindow>(ofGetCurrentWindow()); `
