### ISSUE TITLE
Cannot build due to some errors

### ISSUE THREAD

**Issue by layegning** [elliotwoods/ofxKinectForWindows2#90]
Hello Elliot, 

I've been trying to use your add-on to interact with Kinect V2, when I try to build a project I get at least 11 errors (in the screenshots), and I don't think I know the exact meaning. I am not sure if I missing some steps over here. 
1- I add the add-on through the Project Generator.
2- I add the existing project ofxKinectForWindows2Lib on my VS solution + the prop + the reference (on my own project) as you explain it on the Read me.
For the code itself, I copy and paste the basic example present on your Github Rep.

Windows 10 
Visual Studio 2019

![error](https://user-images.githubusercontent.com/7271650/75986545-2d141000-5ee6-11ea-9ff5-c2ecda50715c.png)

**Comment by elliotwoods** [comment]
Testing here on VS2019 and openFrameworks master branch.
The example builds fine without any issue (just allow VS to upgrade the projects as requested - but it seems you already did that).

My guess is that you're not using the normal openFrameworks path structure (i.e. your app isn't in {OF_BASE}/apps/A/B)?
This is mentioned in the readme as unsupported. Specifically it's not supported by the ofxKinectForWindowsLib.
If you want to keep your paths different, then you'll need to use the project generator and setup all the settings yourself (rather than using the Lib project and the props file). You can open those 2 files in a text editor to see what settings you would need.
